name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: test checkout 
        run: ls 
      - name: Install snapd 
        run:  echo ${{secrets.SUDOPASSWD}}| sudo install snapd
      - name: Install docker 
        run: snap install docker
      - name: remove docker iamges if have
        run: docker rmi -f mypythonenv
      - name: docker build
        run: docker build -f Dockerfile -t mypythonenv . && sudo docker images
      - name: change tag
        run: docker tag mypythonenv ghcr.io/sjcancode/mypythonenv:latest
      - name: test docker build
        run: docker images
