
name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install snapd
        run:  apt install snapd
      - name: Install docker 
        run: snap install docker
