name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install snapd 
        run:  sudo apt install snapd -y
      - name: img build
        run: sudo img build -f Dockerfile -t ghcr.io/${{secrets.GITHUBUSERNAME}}/test . && sudo img ls
#      - name: change tag
#        run: sudo docker tag mypythonenv ghcr.io/${{secrets.GITHUBUSERNAME}}/mypythonenv:latest
#      - name: test docker build
#        run: sudo docker images
#      - name: login github registery
#        run: sudo docker login ghcr.io -u="${{secrets.GITHUBUSERNAME}}" -p="${{secrets.GITHUBTOKEN}}"
#       - name: docker push
#         run: sudo docker push ghcr.io/${{secrets.GITHUBUSERNAME}}/mypythonenv:latest
#       - name: remove docker
#         run: sudo snap remove --purge docker
#       - name: remove snapd 
#         run: sudo apt autoremove --purge snapd -y
        
        
