name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: test checkout 
        run: ls 
      - name: test create file on desktop if it delete when end
        run: touch /home/appsx/Desktop/gitcreatedfile
      - name: Install snapd 
        run:  sudo apt install snapd
      - name: Install docker 
        run: sudo snap install docker
      - name: remove docker iamges if have
        run: sudo docker rmi -f mypythonenv
      - name: docker build
        run: sudo docker build -f Dockerfile -t mypythonenv . && sudo docker images
      - name: change tag
        run: sudo docker tag mypythonenv ghcr.io/sjcancode/mypythonenv:latest
      - name: test docker build
        run: sudo docker images
