
name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test checkout
        run: ls 
      - name: Install snapd
        run:  sudo apt install snapd
      - name: Install docker 
        run: sudo snap install docker
