name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: img pull nginx:1.14.2
        run: sudo img pull nginx:1.14.2
      - name: img change tag
        run: sudo img tag nginx:1.14.2 ghcr.io/${{secrets.GITHUBUSERNAME}}/nginx:imgv1.14.2
      - name: login github registery
        run: sudo img login ghcr.io -u="${{secrets.GITHUBUSERNAME}}" -p="${{secrets.GITHUBTOKEN}}"
      - name: img push
        run: sudo img push ghcr.io/${{secrets.GITHUBUSERNAME}}/nginx:imgv1.14.2
   
#      - name: img build
#        run: sudo img build -f Dockerfile -t ghcr.io/${{secrets.GITHUBUSERNAME}}/test . && sudo img ls
#      - name: login github registery
#        run: sudo img login ghcr.io -u="${{secrets.GITHUBUSERNAME}}" -p="${{secrets.GITHUBTOKEN}}"        
#***************************************************        
#      - name: change tag
#        run: sudo docker tag mypythonenv ghcr.io/${{secrets.GITHUBUSERNAME}}/mypythonenv:latest
#      - name: test docker build
#        run: sudo docker images
#      - name: login github registery
#        run: sudo docker login ghcr.io -u="${{secrets.GITHUBUSERNAME}}" -p="${{secrets.GITHUBTOKEN}}"
#       - name: docker push
#         run: sudo docker push ghcr.io/${{secrets.GITHUBUSERNAME}}/mypythonenv:latest
#       - name: remove docker
#         run: sudo snap remove --purge docker
#       - name: remove snapd 
#         run: sudo apt autoremove --purge snapd -y
        
        
